name: Android Emulator test

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assemblePlayDebugAndroidTest
    - name: Android Emulator test
      uses: ReactiveCircus/android-emulator-runner@v1.0.1
      with:
        api-level: 28
        headless: true
        disable-animations: true
        script: ./gradlew connectedPlayDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=de.test.antennapod.IgnoreOnCi
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-report
        path: app/build/reports/androidTests/connected/flavors/PLAY/
